// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextGame.Engine.Data;

#nullable disable

namespace TextGame.Engine.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("TextGame.Engine.Entities.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int?>("SceneID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("SceneID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TextGame.Engine.Entities.Scene", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Delay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SceneType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("TextGame.Engine.Entities.Image", b =>
                {
                    b.HasOne("TextGame.Engine.Entities.Scene", "Scene")
                        .WithMany()
                        .HasForeignKey("SceneID");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("TextGame.Engine.Entities.Scene", b =>
                {
                    b.HasOne("TextGame.Engine.Entities.Scene", null)
                        .WithMany("Scenes")
                        .HasForeignKey("ParentID");
                });

            modelBuilder.Entity("TextGame.Engine.Entities.Scene", b =>
                {
                    b.Navigation("Scenes");
                });
#pragma warning restore 612, 618
        }
    }
}
